### ISSUE TITLE
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves

### ISSUE THREAD

**Issue by NerdFaisal404** [opentrace-community/opentrace-cloud-functions#34]
#upload
      1) should have valid buckets
    #upload
      ✓ should use a good pin generator

  3 passing (3s)
  1 failing

  1) config.ts
       #upload
         should have valid buckets:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/lover/Downloads/opentrace-cloud-functions/functions/test/opentrace/config.test.ts)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

**Comment by aleman844** [comment]
I had the same problem and i've changed the service account json file for firebase-adminsdk user

**Comment by qtangs** [comment]
@NerdFaisal404, did you manage to solve the issue?
