### ISSUE TITLE
illegal character in authority at index 8: https...

### ISSUE THREAD

**Issue by Jayjerome** [opentrace-community/opentrace-cloud-functions#38]
The app keeps crashing with this error after deploying to firebase functinos
`  Caused by: java.net.URISyntaxException: Illegal character in authority at index 8: https://<asia-east2>-trace-8rbv.cloudfunctions.net/
        at java.net.URI$Parser.fail(URI.java:2893)
        at java.net.URI$Parser.parseAuthority(URI.java:3231)
        at java.net.URI$Parser.parseHierarchical(URI.java:3142)
        at java.net.URI$Parser.parse(URI.java:3098)
        at java.net.URI.<init>(URI.java:584)
        at okhttp3.HttpUrl.uri(HttpUrl.java:379)
        at okhttp3.internal.connection.RouteSelector.resetNextProxy(RouteSelector.java:129) 
        at okhttp3.internal.connection.RouteSelector.<init>(RouteSelector.java:63) 
        at okhttp3.internal.connection.StreamAllocation.<init>(StreamAllocation.java:101) 
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:112) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254) 
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200) 
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
`
Please assist

**Comment by dermdaly** [comment]
<asia-east2> shouldn't be in the URL. Looks like you included it when you shouldn't.

**Comment by Jayjerome** [comment]
What URL are you referring to @dermdaly

**Comment by qtangs** [comment]
@Jayjerome your URL is not valid, should not contain the angle brackets: `https://<asia-east2>..`
