### ISSUE TITLE
Error with Test Function

### ISSUE THREAD

**Issue by blackopsteam** [opentrace-community/opentrace-cloud-functions#8]
npm --prefix functions test

> functions@ test C:\TraceTogether\functions
> mocha -r ts-node/register test/**/*.test.ts

Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail

Error: Failed to read credentials from file "C:\TraceTogether\functions\src\credentials\testdev.json": Error: ENOENT: no such file or directory, open '"C:\TraceTogether\functions\src\credentials\testdev.json"'
    at FirebaseAppError.FirebaseError [as constructor] (C:\TraceTogether\functions\node_modules\firebase-admin\lib\utils\error.js:42:28)
    at FirebaseAppError.PrefixedFirebaseError [as constructor] (C:\TraceTogether\functions\node_modules\firebase-admin\lib\utils\error.js:88:28)
    at new FirebaseAppError (C:\TraceTogether\functions\node_modules\firebase-admin\lib\utils\error.js:123:28)
    at readCredentialFile (C:\TraceTogether\functions\node_modules\firebase-admin\lib\auth\credential.js:383:15)
    at credentialFromFile (C:\TraceTogether\functions\node_modules\firebase-admin\lib\auth\credential.js:362:27)
    at Object.getApplicationDefault (C:\TraceTogether\functions\node_modules\firebase-admin\lib\auth\credential.js:281:16)
    at FirebaseNamespaceInternals.initializeApp (C:\TraceTogether\functions\node_modules\firebase-admin\lib\firebase-namespace.js:61:47)
    at FirebaseNamespace.initializeApp (C:\TraceTogether\functions\node_modules\firebase-admin\lib\firebase-namespace.js:409:30)
    at Object.<anonymous> (C:\TraceTogether\functions\test\index.test.ts:10:9)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Module.m._compile (C:\TraceTogether\functions\node_modules\ts-node\src\index.ts:836:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Object.require.extensions.<computed> [as .ts] (C:\TraceTogether\functions\node_modules\ts-node\src\index.ts:839:12)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at requireOrImport (C:\TraceTogether\functions\node_modules\mocha\lib\esm-utils.js:15:12)
    at Object.exports.loadFilesAsync (C:\TraceTogether\functions\node_modules\mocha\lib\esm-utils.js:28:26)
    at Mocha.loadFilesAsync (C:\TraceTogether\functions\node_modules\mocha\lib\mocha.js:351:19)
    at singleRun (C:\TraceTogether\functions\node_modules\mocha\lib\cli\run-helpers.js:107:15)
    at exports.runMocha (C:\TraceTogether\functions\node_modules\mocha\lib\cli\run-helpers.js:144:11)
    at Object.exports.handler (C:\TraceTogether\functions\node_modules\mocha\lib\cli\run.js:306:11)
    at Object.runCommand (C:\TraceTogether\functions\node_modules\yargs\lib\command.js:242:26)
    at Object.parseArgs [as _parseArgs] (C:\TraceTogether\functions\node_modules\yargs\yargs.js:1096:28)
    at Object.parse (C:\TraceTogether\functions\node_modules\yargs\yargs.js:575:25)
    at Object.exports.main (C:\TraceTogether\functions\node_modules\mocha\lib\cli\cli.js:68:6)
    at Object.<anonymous> (C:\TraceTogether\functions\node_modules\mocha\bin\mocha:133:29)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! Test failed.  See above for more details.

I have generated a JSON key for local but i am getting the following error. Any ideas?

**Comment by mchmielarski** [comment]
https://firebase.google.com/docs/functions/config-env#automatically_populated_environment_variables

**Comment by blackopsteam** [comment]
thanks mchmielarski

a follow up question to this, do i declare the FIREBASE_CONFIG and GCLOUD_PROJECT environment variables in the config.ts file located in \functions\src folder? sorry for my ignorance. since i am pretty new in this and not much documentation is included in the write up under https://github.com/opentrace-community/opentrace-cloud-functions#test. 

Unfortunately, i need some help in this area everyone! Please be patient with me. I am only trying to do this because no one has the initiative in our country to do this to fight against covid.

not sure after the configuration where i will add those variables. 

help.

**Comment by blackopsteam** [comment]
this is the content of the config.ts

import FunctionConfig from "./opentrace/types/FunctionConfig";
import Authenticator from "./opentrace/utils/Authenticator";
import PinGenerator from "./opentrace/utils/PinGenerator";

const config: FunctionConfig = {
  projectId: "tracetogether-philippines",
  regions: ["asia-east2"],
  utcOffset: 0,
  authenticator: new Authenticator(),
  encryption: {
    defaultAlgorithm: "aes-256-gcm",
    keyPath: "./credentials/testdev.json",
    defaultVersion: 1,
  },
  tempID: {
    validityPeriod: 0.25, // in hours
    refreshInterval: 12,  // in hours
    batchSize: 100, // sufficient for 24h+
  },
  upload: {
    pinGenerator: new PinGenerator(),
    bucket: "upload-bucket-ttph", //
    recordsDir: "records",
    testsDir: "tests",
    tokenValidityPeriod: 2, // in hours
    bucketForArchive: "archive-bucket-ttph",
  },
};

export default config;

**Comment by blackopsteam** [comment]
or should i replace in the keypath the values :
projects/**************/secrets/TraceTogetherSecret 
or 
just the name TraceTogetherSecret 

located in the google cloud under Secret Manager?

**Comment by blackopsteam** [comment]
thanks for your patience

**Comment by mchmielarski** [comment]
you can set env variables in many ways, but remember that it's only required by your local environment. so that easiest way is to add them before command which you try to run:
`FIREBASE_CONFIG=... GCLOUD_PROJECT=... npm --prefix functions test`

**Comment by qtangs** [comment]
In our setup we don't use `FIREBASE_CONFIG` and `GCLOUD_PROJECT`.
@tophatxperts, did you set `GOOGLE_APPLICATION_CREDENTIALS` variable to `"C:\TraceTogether\functions\src\credentials\testdev.json"`? Do ensure that the file exists and is a valid [GCP credential file](https://cloud.google.com/docs/authentication/production).

And `keyPath` should be set to `TraceTogetherSecret` in your case.
